// components/ProjectGrid.vue
<script setup lang="ts">
import type { Project } from '../src/types';

defineProps<{
  projects: Project[];
}>();
</script>

<template>
  <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
    <ProjectCard v-for="project in projects" :key="project.id" :project="project" />
  </div>
</template>

// src/components/projects/ProjectGrid.tsx
import type { Project } from '../../types';
import { ProjectCard } from './ProjectCard';

interface ProjectGridProps {
  projects: Project[];
}

export function ProjectGrid({ projects }: ProjectGridProps) {
  return (
    <div className="grid gap-6 lg:grid-cols-2">
      {projects.map((project) => (
        <ProjectCard key={project.id} project={project} />
      ))}
    </div>
  );
}
