// components/ProjectCard.vue
<script setup lang="ts">
import type { Project } from '../src/types';

defineProps<{
  project: Project;
}>();
</script>

<template>
  <a
    v-if="project.repositoryPublic && project.githubUrl"
    :href="project.githubUrl"
    target="_blank"
    rel="noreferrer"
    :aria-label="`${project.title} on GitHub`"
    class="group flex min-h-[11rem] flex-col rounded-xl border border-border bg-card p-2.5 text-left text-card-foreground shadow-sm shadow-black/10 transition duration-300 hover:border-ring/30 hover:shadow-md hover:-translate-y-0.5 dark:shadow-black/20"
  >
    <div class="flex flex-1 flex-col">
      <h3 class="mb-2 text-base font-semibold leading-snug text-card-foreground">
        {{ project.title }}
      </h3>
      <p class="flex-1 text-sm leading-[1.4] text-muted-foreground">
        {{ project.shortDescription }}
      </p>
      <div class="flex flex-wrap gap-1" :aria-label="`${project.title} technologies`">
        <UiTag v-for="technology in project.technologies" :key="technology">
          {{ technology }}
        </UiTag>
      </div>
    </div>
  </a>
  <article
    v-else
    class="group flex min-h-[11rem] flex-col rounded-xl border border-border bg-card p-2.5 text-left text-card-foreground shadow-sm shadow-black/10 transition duration-300 dark:shadow-black/20"
  >
    <div class="flex flex-1 flex-col">
      <h3 class="mb-2 text-base font-semibold leading-snug text-card-foreground">
        {{ project.title }}
      </h3>
      <p class="flex-1 text-sm leading-[1.4] text-muted-foreground">
        {{ project.shortDescription }}
      </p>
      <div class="flex flex-wrap gap-1" :aria-label="`${project.title} technologies`">
        <UiTag v-for="technology in project.technologies" :key="technology">
          {{ technology }}
        </UiTag>
      </div>
    </div>
  </article>
</template>

// src/components/projects/ProjectCard.tsx
import type { Project } from '../../types';
import { Button } from '../ui/Button';
import { Tag } from '../ui/Tag';

interface ProjectCardProps {
  project: Project;
}

const categoryLabels: Record<Project['category'], string> = {
  'data-engineering': 'Data Engineering',
  ai: 'AI',
  ml: 'Machine Learning',
  'emg-signals': 'EMG Signals'
};

export function ProjectCard({ project }: ProjectCardProps) {
  return (
    <article className="flex h-full flex-col overflow-hidden rounded-3xl border border-white/10 bg-slate-950/70 shadow-2xl shadow-slate-950/30 transition hover:border-sky-300/50">
      {project.image ? (
        <img
          src={project.image.src}
          alt={project.image.alt}
          className="h-48 w-full object-cover"
          loading="lazy"
        />
      ) : null}
      <div className="flex flex-1 flex-col p-6">
        <p className="text-xs font-semibold uppercase tracking-[0.22em] text-sky-300">
          {categoryLabels[project.category]}
        </p>
        <h2 className="mt-3 text-2xl font-semibold tracking-tight text-white">{project.title}</h2>
        <p className="mt-3 flex-1 text-sm leading-6 text-slate-300">{project.shortDescription}</p>
        <div className="mt-5 flex flex-wrap gap-2" aria-label={`${project.title} technologies`}>
          {project.technologies.map((technology) => (
            <Tag key={technology}>{technology}</Tag>
          ))}
        </div>
        <div className="mt-6 flex flex-col gap-3 sm:flex-row">
          <Button href={`/projects/${project.id}`} aria-label={`View details for ${project.title}`}>
            View details
          </Button>
          {project.repositoryPublic && project.githubUrl ? (
            <Button
              href={project.githubUrl}
              variant="secondary"
              external
              aria-label={`Open GitHub repository for ${project.title}`}
            >
              Repository
            </Button>
          ) : (
            <span className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/5 px-5 py-3 text-sm font-semibold text-slate-300">
              Repository unavailable
            </span>
          )}
        </div>
      </div>
    </article>
  );
}
